version: 2.1

jobs:
  test:
    docker:
      - image: circleci/18.15.0-browse
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: 'yarn install'
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Lint
          command: 'yarn lint'

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
